Repository FHIDev/Fhi.VersionApiClient, pull requests merged in 2025-03, with the labels that each got.

#18 Tests with WebApplicationFactory throws error when using environment with IHostEnvironment
  Fhi.VersionApiClient/Fhi.VersionApiClient.csproj
  Fhi.VersionApiClient/VersionService.cs
Labels: bug

#20 Update Microsoft.Extensions.* from 9.0.0 to 9.0.3
  Fhi.VersionApiClient/Fhi.VersionApiClient.csproj
Labels: dependencies

#22 Release 2.3.0
  Fhi.VersionApiClient/Fhi.VersionApiClient.csproj
Labels: internal
